import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { mkdir, rename, rm, stat } from "node:fs/promises";

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const thirdParty = join(root, "third_party");

async function run(command: string[], cwd?: string) {
  const process = Bun.spawn(command, {
    cwd,
    stdout: "inherit",
    stderr: "inherit",
  });
  const exitCode = await process.exited;

  if (exitCode !== 0) {
    throw new Error(`Command failed (${exitCode}): ${command.join(" ")}`);
  }
}

type Dependency = {
  directory: string;
  repository: string;
  revision: string;
  sparsePaths: string[];
};

const dependencies: Dependency[] = [
  {
    directory: "SDL",
    repository: "https://github.com/libsdl-org/SDL.git",
    revision: process.env.SDL_REVISION ?? "main",
    sparsePaths: ["/CMakeLists.txt", "/cmake/", "/include/", "/src/", "/build-scripts/", "/android-project/"],
  },
  {
    directory: "SDL_image",
    repository: "https://github.com/libsdl-org/SDL_image.git",
    revision: process.env.SDL_IMAGE_REVISION ?? "main",
    sparsePaths: ["/CMakeLists.txt", "/cmake/", "/include/", "/src/", "/external/", "/build-scripts/"],
  },
  {
    directory: "freetype",
    repository: "https://github.com/freetype/freetype.git",
    revision: process.env.FREETYPE_REVISION ?? "master",
    sparsePaths: ["/CMakeLists.txt", "/README", "/LICENSE.TXT", "/builds/", "/include/", "/src/"],
  },
  {
    directory: "quickjs",
    repository: "https://github.com/quickjs-ng/quickjs.git",
    revision: process.env.QUICKJS_REVISION ?? "master",
    sparsePaths: ["/CMakeLists.txt", "/*.c", "/*.h", "/*.cmake", "/cmake/", "/gen/", "/include/", "/src/"],
  },
  {
    directory: "box2d",
    repository: "https://github.com/erincatto/box2d.git",
    revision: process.env.BOX2D_REVISION ?? "main",
    sparsePaths: ["/CMakeLists.txt", "/cmake/", "/include/", "/src/"],
  },
];

function moduleCmake(dependency: Dependency) {
  const variable = dependency.directory.toUpperCase().replace(/[^A-Z0-9]/g, "_");
  return `# Generated by scripts/setup-safex.ts. Do not edit.\n\
# Keep the vendored build focused on implementation and public headers.\n\
file(GLOB_RECURSE SAFEX_${variable}_SOURCES CONFIGURE_DEPENDS\n\
  "\${CMAKE_CURRENT_LIST_DIR}/src/*.c"\n\
  "\${CMAKE_CURRENT_LIST_DIR}/src/*.cc"\n\
  "\${CMAKE_CURRENT_LIST_DIR}/src/*.cpp"\n\
  "\${CMAKE_CURRENT_LIST_DIR}/*.c"\n\
)\n\
file(GLOB_RECURSE SAFEX_${variable}_HEADERS CONFIGURE_DEPENDS\n\
  "\${CMAKE_CURRENT_LIST_DIR}/include/*.h"\n\
  "\${CMAKE_CURRENT_LIST_DIR}/src/*.h"\n\
  "\${CMAKE_CURRENT_LIST_DIR}/*.h"\n\
)\n\
include("\${CMAKE_CURRENT_LIST_DIR}/upstream-CMakeLists.txt")\n`;
}

async function writeModuleCmake(dependency: Dependency) {
  const destination = join(thirdParty, dependency.directory);
  const cmake = join(destination, "CMakeLists.txt");
  const upstreamCmake = join(destination, "upstream-CMakeLists.txt");

  try {
    await stat(upstreamCmake);
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error;
    await rename(cmake, upstreamCmake);
  }

  await Bun.write(cmake, moduleCmake(dependency));
}

async function restoreUpstreamCmake(destination: string) {
  try {
    await stat(join(destination, "upstream-CMakeLists.txt"));
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") return;
    throw error;
  }

  // CMakeLists.txt is tracked by the dependency. Restore it before checking
  // out a new revision so Git never has to overwrite our generated wrapper.
  await run(["git", "checkout", "--", "CMakeLists.txt"], destination);
  await rm(join(destination, "upstream-CMakeLists.txt"));
}

async function cloneDependency(dependency: Dependency) {
  const { directory, repository, revision, sparsePaths } = dependency;
  const destination = join(thirdParty, directory);

  try {
    await stat(join(destination, ".git"));
    console.log(`Updating ${directory}`);
    await run(["git", "sparse-checkout", "set", "--no-cone", ...sparsePaths], destination);
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== "ENOENT") {
      throw error;
    }
    console.log(`Downloading ${directory}`);
    await mkdir(destination, { recursive: true });
    await run(["git", "init"], destination);
    await run(["git", "remote", "add", "origin", repository], destination);
    await run(["git", "sparse-checkout", "init", "--no-cone"], destination);
    await run(["git", "sparse-checkout", "set", "--no-cone", ...sparsePaths], destination);
  }

  await restoreUpstreamCmake(destination);
  await run(["git", "fetch", "--depth", "1", "origin", revision], destination);
  await run(["git", "checkout", "--detach", "FETCH_HEAD"], destination);
  await run(["git", "submodule", "update", "--init", "--recursive", "--depth", "1", "--filter=blob:none"], destination);
  await writeModuleCmake(dependency);
}

async function bootstrapNativeDependencies() {
  await mkdir(thirdParty, { recursive: true });
  for (const dependency of dependencies) {
    await cloneDependency(dependency);
  }
  console.log("Native dependency sources are ready in third_party/.");
}

async function configureUnixEnvironment() {
  if (process.env.SAFEX_ROOT) {
    console.log(`SAFEX_ROOT is already set to: ${process.env.SAFEX_ROOT}`);
    return;
  }

  const home = process.env.HOME;
  if (!home) {
    throw new Error("HOME is required to configure SAFEX_ROOT.");
  }

  const shell = process.env.SHELL ?? "";
  const profileName = process.platform === "darwin"
    ? shell === "/bin/zsh" ? ".zshrc" : ".bash_profile"
    : shell.endsWith("/zsh") ? ".zshrc" : shell.endsWith("/bash") ? ".bashrc" : ".profile";
  const profile = join(home, profileName);
  const setting = `export SAFEX_ROOT=\"${root}\"`;
  const existing = (await Bun.file(profile).exists()) ? await Bun.file(profile).text() : "";

  if (!existing.split(/\r?\n/).includes(setting)) {
    await Bun.write(profile, `${existing}${existing.endsWith("\n") || !existing ? "" : "\n"}\n${setting}\n`);
  }

  console.log(`Added SAFEX_ROOT to ${profile}. Open a new terminal or run: . ${profile}`);
}

async function configureWindowsEnvironment() {
  await run(["setx", "SAFEX_ROOT", root]);
  console.log("Added SAFEX_ROOT. Restart your command-line application.");
}

if (process.platform === "darwin" || process.platform === "linux") {
  await bootstrapNativeDependencies();
  await configureUnixEnvironment();
} else if (process.platform === "win32") {
  await bootstrapNativeDependencies();
  await configureWindowsEnvironment();
} else {
  throw new Error("setup-safex.ts supports macOS, Linux, and Windows only.");
}
